name: GCS Deploy

on:
  push:
    branches: [master, actions]

permissions:
  contents: 'read'
  id-token: 'write'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # actions/checkout MUST come before auth.
    - id: 'checkout'
      uses: 'actions/checkout@v3'

    # Authenticate through Workload Identity Federation.
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/399495472921/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-actions@studious-works-380917.iam.gserviceaccount.com'

    # ... further steps are automatically authenticated.

    - id: 'Package Dependencies'
      run: make build

    - id: 'Deploy to GCS'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: 'dist/'
        destination: 'spark-jobs'
