name: Upload to S3

on:
  push:
    branches:
      - master 
    tags:
      - v*

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      
      - name: Build
        run: make build

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

      - name: Upload to S3
	uses: shallwefootball/s3-upload-action@master
	with:
	  aws_key_id: ${{ secrets.AWS_ACCESS_KEY }}
	  aws_secret_access_key: ${{ secrets.AWS_SECRET_KEY}}
	  aws_bucket: pyspark-boilerplate
	  source_dir: dist
